### ISSUE TITLE
Spacing for - operator around negative numbers

### ISSUE THREAD

**Issue by tsafavi** [TheWolfA2/183lint#1]
When submitting a file with this line of code: 

```
return x >= -9 && x <= 9;
```

I received the message "Incorrect spacing around - operator."

**Comment by TheWolfA2** [comment]
Ugh. So what's happening is the Abstract Syntax Tree that's generated by Clang treats the beginning column of the `&&` as where the first operand starts. Then, the AST picks up on the `>=` after it, since it's a child in the tree. Basically, it's an issue that tree is being read DFS style, but are being added and evaluated in pre-order

**Comment by TheWolfA2** [comment]
5284d9927282321c1231d643abb88ede6eec2352
