### ISSUE TITLE
Incorrect spacing reported around < when << is used

### ISSUE THREAD

**Issue by amirkamil** [TheWolfA2/183lint#8]
Here is the source line:
```
        cout << "Choice is: " << choice << endl;
```
And the error message:
```
Line 122, Column 31: Incorrect spacing around < operator.
```

**Comment by TheWolfA2** [comment]
Decided I should describe how the bug came about.  It occurred from cleaning the literal strings and chars in a line of code. The replacement caused the strings to shorten, meaning the actual column the operator was sitting in no longer matched the string (if it occurred after a string/char removal)
